export enum EAction {
    FLIP_CARD = 'FLIP_CARD',
    CHECK_MATCH = 'CHECK_MATCH',
    RESET_FLIPPED = 'RESET_FLIPPED',
    RESET_GAME = 'RESET_GAME',
    UPDATE_SCORE_AND_RECORD = 'UPDATE_SCORE_AND_RECORD',
}
